global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape metrics from OpenTelemetry Collector
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
    scrape_interval: 5s

  # Uncomment when app service is running in Docker
  # - job_name: "fastapi"
  #   static_configs:
  #     - targets: ["app:8000"]
  #   metrics_path: "/metrics"
  #   scrape_interval: 5s